package it.eng.consolepec.spagicclient.bean.request.fascicolo;

import it.eng.consolepec.spagicclient.bean.request.Request;
import it.eng.consolepec.spagicclient.bean.request.datiaggiuntivi.DatoAggiuntivo;

import java.util.ArrayList;
import java.util.List;

import lombok.Getter;
import lombok.Setter;

public abstract class GenericFascicoloRequest implements Request {

	@Getter
	@Setter
	private String titolo, note, assegnatario, pathPraticaDaCollegare, idDocumentale, destination;

	@Getter
	@Setter
	private List<DatoAggiuntivo> datiAggiuntivi = new ArrayList<DatoAggiuntivo>();
	
	public enum TipoFascicoloRequest {
		FASCICOLO_PERSONALE, 
		FASCICOLO_RISERVATO, 
		FASCICOLO_ALBO_PRETORIO, 
		FASCICOLO_GARE, 
		FASCICOLO_GARE_ATTI, 
		FASCICOLO_GARE_CONTRATTI, 
		FASCICOLO_GARE_SUBAPPALTO, 
		FASCICOLO_DOMINO, 
		FASCICOLO_FATTURAZIONE_ELETTRONICA, 
		FASCICOLO_CONTRASSEGNO, 
		FASCICOLO_MODULISTICA,
		FASCICOLO_ENTRATE_RISCOSSIONE,
		FASCICOLO_ENTRATE_PUBBLICITA_AUTORIZZAZIONE,
		FASCICOLO_ENTRATE_ACCESSO_ATTI,
		FASCICOLO_ENTRATE_ICI_IMU_TASI,
		FASCICOLO_ENTRATE_TARSU_TARES_TARI,
		FASCICOLO_ENTRATE_SANZIONI_AMMINISTRATIVE,
		FASCICOLO_ENTRATE_IMPOSTE_SOGGIORNO, 
		FASCICOLO_ENTRATE_CONTENZIOSO, 
		FASCICOLO_ENTRATE_CONTENZIOSO_GENERICO,
		FASCICOLO_ENTRATE_RISCOSSIONE_GENERICO,
		FASCICOLO_ENTRATE_GENERICO,
		FASCICOLO_ENTRATE_FALLIMENTI,
		FASCICOLO_SPORT_BORGOPANIGALE,
		FASCICOLO_SPORT_NAVILE,
		FASCICOLO_SPORT_PORTO,
		FASCICOLO_SPORT_RENO,
		FASCICOLO_SPORT_SANDONATO,
		FASCICOLO_SPORT_SANTOSTEFANO,
		FASCICOLO_SPORT_SANVITALE,
		FASCICOLO_SPORT_SARAGOZZA,
		FASCICOLO_SPORT_SAVENA,
		FASCICOLO_SPORT_BORGOPANIGALE_RENO,
		FASCICOLO_SPORT_PORTO_SARAGOZZA,
		FASCICOLO_SPORT_SANDONATO_SANVITALE,
		FASCICOLO_SALUTE_SPORT,
		FASCICOLO_ORDINI,
		FASCICOLO_ENTRATE_DIREZIONE,
		FASCICOLO_ACCESSO_ATTI,
		FASCICOLO_TSO,
		FASCICOLO_ELETTORALE_ELETTORE,
		FASCICOLO_ELETTORALE_COMUNICAZIONI,
		FASCICOLO_ELETTORALE_GENERICO,
		FASCICOLO_ENTRATE_ISEE,
		//FASCICOLO_URBANISTICA,
		FASCICOLO_PRG,
		FASCICOLO_PIANI_URBANISTICI_DIVERSI,
		FASCICOLO_CATASTO_SIT_CARTOGRAFIA,
		FASCICOLO_PSC_VARIANTI,
		FASCICOLO_POC_VARIANTI,
		FASCICOLO_RUE_VARIANTI,
		FASCICOLO_PUA,
		//FASCICOLO_ALTRI_STRUMENTI,
		FASCICOLO_GENERICHE,
		FASCICOLO_ISTRUTTORIA_H,
		FASCICOLO_AUTOTUTELE,
		FASCICOLO_RESI,
		FASCICOLO_SCARTI_RECUPERO,
		FASCICOLO_GENERICO;
	}

	public abstract TipoFascicoloRequest getTipo();
}
